version: 0.2
phases:
  install:
    commands:
      - echo update npm...
      # - npm install --location=global
      # - npm update --location=global npm
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install --location=global yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Pre_build Phase
      # - yarn install
  build:
    commands:
      - echo Build Phase
      - yarn run build

  post_build:
    commands:
      - echo PostBuild Phase

artifacts:
  files:
    - '**/*'
  discard-path: no
  base-directory: build
